### ISSUE TITLE
Source map support

### ISSUE THREAD

**Issue by sponge** [koush/vscode-quickjs-debug#2]
I assume VSCode is able to handle source maps by parsing them out of the source code and grabbing them. Is it just a matter of finding the right call in VSC to use source maps from the browser/node based debugger? I wouldn't mind hacking it in, I'm just not sure how much of the work already exists in VSC itself. Has anyone ever looked into this?

**Comment by stgatilov** [comment]
I guess source map support would make it possible to work with typescript code on quickjs.

**Comment by sponge** [comment]
Pretty much! I am using TS currently and given QuickJS' support the generated source is very close to the original source but its still just different enough to be annoying.

**Comment by swankjesse** [comment]
FYI, in Zipline we wrote some code to combine compiled QuickJS bytecode and a sourcemap to produce new QuickJS bytecode. It's not currently set up to be reused for typescript, but it should be possible to use that code to achieve this goal. Or just use this implementation strategy.

https://github.com/cashapp/zipline/blob/trunk/zipline-bytecode/src/test/kotlin/app/cash/zipline/bytecode/ApplySourceMapToBytecodeTest.kt

**Comment by koush** [comment]
> I assume VSCode is able to handle source maps by parsing them out of the source code and grabbing them. Is it just a matter of finding the right call in VSC to use source maps from the browser/node based debugger? I wouldn't mind hacking it in, I'm just not sure how much of the work already exists in VSC itself. Has anyone ever looked into this?

Yes, this debug adapter supports source maps, including typescript source maps (which is the language I was using with quickjs). It is unnecessary to have the source maps in the runtime itself. I am trying to stay as close to upstream as possible.

**Comment by koush** [comment]
it works like the typical source map entry in other vs code projects.

https://github.com/koush/vscode-quickjs-debug/blob/4984e37c77ed1403dff95ed0accb0ad6a4b1c8b5/package.json#L187
